Repository hmcts/bar-web, pull requests merged in 2018-10, with the labels that each got.

#308 Bar-243 recreated after angular 6 merge
  src/app/core/components/payment-overview/payment-overview.component.html
  src/app/core/components/payment-overview/payment-overview.component.ts
  src/app/core/services/paymentoverview/paymentsoverview.service.ts
Labels: ns:bar-web-pr-308

#313 Bar 382
  config/custom-environment-variables.yaml
  config/default.yaml
  express/app.js
  express/mvc/controllers/FeeController.js
  express/services/FeeService.js
  express/test/services/FeeService.test.js
  infrastructure/main.tf
  kubernetes/config.aat.yaml
  src/app/core/components/feelogedit/detail/feedetail.component.html
  src/app/core/components/feelogedit/detail/feedetail.component.spec.ts
  src/app/core/components/feelogedit/detail/feedetail.component.ts
  src/app/core/components/feelogedit/feelogedit.component.html
  src/app/core/components/feelogedit/feelogedit.component.scss
  src/app/core/components/feelogedit/feelogedit.component.spec.ts
  src/app/core/components/feelogedit/feelogedit.component.ts
  src/app/core/services/feelog/feelog.service.ts
  src/app/core/test-mocks/feelog.service.mock.ts
  src/app/test-utils/feelog-edit-content.ts
Labels: ns:bar-web-pr-313

#317 Added comment to trigger the redeploy of terraform
  infrastructure/main.tf
Labels: ns:bar-web-pr-317

#321 Fixed the smoke test URL
  bin/run-smoke-test.sh
  package.json
  smoke-test/smoke-codecept.conf.js
Labels: ns:bar-web-pr-321

#309 [SCD][BAR-491]
  express/mvc/controllers/PaymentInstructionController.js
  src/app/core/components/check-submit/check-submit.component.ts
  src/app/core/components/paymentslog/paymentslog.component.ts
  src/app/shared/components/details/details.component.html
  src/app/shared/components/details/details.component.spec.ts
  src/app/shared/components/details/details.component.ts
Labels: ns:bar-web-pr-309
