Repository hmcts/bar-web, pull requests merged in 2018-12, with the labels that each got.

#369 Fixed functional test login page loading issue
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/BARDeliveryManager_test.js
  acceptance-tests/test/end-to-end/tests/BARFeeClerk_test.js
  acceptance-tests/test/end-to-end/tests/BARPostClerk_test.js
Labels: ns:bar-web-pr-369

#367 Bug fixes
  .eslintignore
  README.md
  src/app/core/components/feelogedit/feelogedit.component.ts
  src/app/core/components/feelogedit/main/feelog.main.component.html
  src/app/core/components/feelogedit/main/feelog.main.component.spec.ts
  src/app/core/components/feelogedit/main/feelog.main.component.ts
  src/app/core/components/payment-instruction-list/payment-instruction-list.component.html
  src/app/core/services/payment-instructions/payment-instructions.service.ts
  src/app/shared/components/payment-instruction-grid/payment-instruction-grid.component.html
  src/app/shared/components/payment-instruction-grid/payment-instruction-grid.component.ts
  src/app/test-utils/test-utils.ts
Labels: ns:bar-web-pr-367

#371 Implemented BAR-555
  src/app/core/components/feelogedit/detail/feedetail.component.html
  src/app/core/components/feelogedit/detail/feedetail.component.ts
Labels: ns:bar-web-pr-371

#372 Added new functional test
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/BARFeeClerk_test.js
  src/app/core/components/feelogedit/detail/feedetail.component.html
  src/app/core/components/feelogedit/detail/feedetail.component.spec.ts
  src/app/core/components/feelogedit/detail/feedetail.component.ts
  src/app/core/components/feelogedit/main/feelog.main.component.html
Labels: ns:bar-web-pr-372

#374 Remove nsp
  .travis.yml
  infrastructure/main.tf
  package.json
  yarn.lock
Labels: ns:bar-web-pr-374

#375 fix sonar coverage issue
  src/app/core/components/feelogedit/feelogedit.component.spec.ts
  src/app/core/models/payment.type.enum.spec.ts
  src/app/core/models/payment.type.enum.ts
Labels: ns:bar-web-pr-375
