Repository hmcts/bar-web, pull requests merged in 2018-11, with the labels that each got.

#310 [SCD][BAR-484]
  .dockerignore
  Dockerfile
  src/app/core/components/check-submit/check-submit.component.spec.ts
  src/app/core/components/error/error.component.spec.ts
  src/app/shared/components/payment-instruction-grid/payment-instruction-grid.component.html
  src/app/shared/components/payment-instruction-grid/payment-instruction-grid.component.spec.ts
Labels: ns:bar-web-pr-310

#327 Implemented BAR-493
  express/services/FeeService.js
  express/test/services/FeeService.test.js
  src/app/core/components/feelogedit/detail/feedetail.component.html
  src/app/core/components/feelogedit/detail/feedetail.component.ts
  src/app/core/services/feelog/feelog.service.spec.ts
  src/app/core/services/feelog/feelog.service.ts
  src/app/core/test-mocks/feelog.service.mock.ts
  src/app/shared/components/details/details.component.ts
Labels: ns:bar-web-pr-327

#329 [SCD] Payment log change
  src/app/core/components/paymentslog/paymentslog.component.ts
  src/app/core/services/paymentslog/paymentslog.service.spec.ts
  src/app/core/services/paymentslog/paymentslog.service.ts
Labels: ns:bar-web-pr-329

#330 Bar 481 & Bar 482
  infrastructure/demo.tfvars
  infrastructure/main.tf
  src/app/core/components/feelogedit/feelogedit.component.html
  src/app/core/components/feelogedit/feelogedit.component.scss
  src/app/core/components/feelogedit/feelogedit.component.spec.ts
  src/app/core/components/feelogedit/feelogedit.component.ts
  src/app/core/components/feelogedit/main/feelog.main.component.html
  src/app/core/components/feelogedit/main/feelog.main.component.ts
  src/app/core/interfaces/payments-log.ts
  src/app/core/models/paymentinstruction.model.ts
  src/app/core/models/returnreason.model.spec.ts
  src/app/core/models/returnreason.model.ts
Labels: ns:bar-web-pr-330

#318 BAR-396 withdrawn and returned pi set to 'Completed'
  src/app/core/models/paymentaction.model.ts
  src/app/core/models/paymentstatus.model.ts
  src/app/core/services/payment-instructions/payment-instructions.service.ts
  src/app/shared/components/details/details.component.html
  src/app/shared/components/details/details.component.ts
Labels: ns:bar-web-pr-318

#328 [BAR-478][AK] display calculate on fee select, force number on editor
  src/app/core/components/feelogedit/detail/feedetail.component.html
  src/app/core/components/feelogedit/detail/feedetail.component.spec.ts
  src/app/core/components/feelogedit/detail/feedetail.component.ts
  src/app/core/models/feesearch.model.spec.ts
  src/app/core/models/feesearch.model.ts
Labels: ns:bar-web-pr-328

#331 [SCD][BAR-386]
  src/app/shared/components/action-filter/action-filter.component.html
  src/app/shared/components/navigation/navigation.component.html
Labels: ns:bar-web-pr-331

#339 Removed the dev certs folder
  dev-certificates/localhost.cert
  dev-certificates/localhost.key
Labels: ns:bar-web-pr-339

#340 [SCD][BAR-509]
  src/app/core/components/payment-instruction/payment-instruction.component.html
  src/app/core/components/payment-instruction/payment-instruction.component.spec.ts
  src/app/core/components/payment-instruction/payment-instruction.component.ts
Labels: ns:bar-web-pr-340

#338 [SCD][BAR-104]
  express/services/PaymentsLogService.js
  src/app/core/components/feelogedit/feelogedit.component.spec.ts
  src/app/core/services/paymentslog/paymentslog.service.ts
  src/app/shared/components/navigation/navigation.component.html
  src/app/shared/components/navigation/navigation.component.ts
  src/app/shared/services/state/paymentstate.service.ts
Labels: ns:bar-web-pr-338

#343 BAR-385
  src/app/core/components/payment-instruction-list/payment-instruction-list.component.html
  src/app/core/components/payment-review/payment-review.component.html
  src/app/core/components/paymentslog/paymentslog.component.html
  src/app/core/components/search-results/search-results.component.html
  src/app/shared/components/details/details.component.html
  src/app/shared/components/details/details.component.scss
  src/app/shared/components/navigation/navigation.component.html
  src/app/shared/components/payment-instruction-grid/payment-instruction-grid.component.html
  src/app/shared/components/payment-instruction-grid/payment-instruction-grid.component.scss
  src/app/shared/directives/numbers-only/numbers-only.directive.spec.ts
Labels: ns:bar-web-pr-343

#344 Added tests
  src/app/core/test-mocks/payment-instruction.service.mock.ts
  src/app/core/test-mocks/user.service.mock.ts
  src/app/shared/components/navigation/navigation.component.spec.ts
  src/app/shared/directives/numbers-only/numbers-only.directive.spec.ts
Labels: ns:bar-web-pr-344

#347 [SCD][BAR-README]
  README.md
Labels: ns:bar-web-pr-347

#348 BAR-440 label changes
  package.json
  src/app/core/components/payment-overview/payment-overview.component.html
  src/app/shared/components/details/details.component.html
Labels: ns:bar-web-pr-348

#345 [BAR-476][AK] integrate appinsights in angular
  Jenkinsfile_CNP
  express/app.js
  express/mvc/controllers/PaymentsLogController.js
  express/test/mvc/controllers/PaymentInstructionController.test.js
  kubernetes/deployment.template.yaml
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/core/components/reporting/reporting.component.html
  src/app/core/components/reporting/reporting.component.ts
  src/app/shared/services/appinsights/monitoring.service.spec.ts
  src/app/shared/services/appinsights/monitoring.service.ts
  yarn.lock
Labels: ns:bar-web-pr-345

#332 [BAR-280][AK] senior fee clerk overview based on actions
  express/services/PaymentInstructionService.js
  express/test/mvc/controllers/PaymentInstructionController.test.js
  express/test/services/PaymentInstructionService.mock.js
  express/test/services/PaymentInstructionService.test.js
  src/app/core/components/payment-review-summary/payment-review-summary.component.html
  src/app/core/components/payment-review-summary/payment-review-summary.component.spec.ts
  src/app/core/components/payment-review-summary/payment-review-summary.component.ts
  src/app/core/interfaces/payment.statistics.ts
  src/app/core/services/paymentslog/paymentslog.service.ts
  src/app/core/test-mocks/payment-log.service.mock.ts
  src/app/core/test-mocks/paymentsoverview.service.mock.ts
  src/app/core/test-mocks/paymentstate.service.mock.ts
  src/app/shared/components/details/details.component.html
  src/app/shared/components/details/details.component.spec.ts
  src/app/shared/components/details/details.component.ts
  src/app/shared/components/stats/stats.component.html
  src/app/shared/components/stats/stats.component.spec.ts
  src/app/shared/components/stats/stats.component.ts
  src/app/shared/directives/numbers-only/numbers-only.directive.spec.ts
  src/app/shared/services/state/paymentstate.service.ts
Labels: ns:bar-web-pr-332

#342 [SCD][BAR-512]
  src/app/core/components/check-submit/check-submit.component.ts
  src/app/core/services/payment-instructions/payment-instructions.service.ts
  src/app/shared/components/payment-instruction-grid/payment-instruction-grid.component.html
  src/app/shared/components/payment-instruction-grid/payment-instruction-grid.component.ts
  src/app/shared/services/util/util.service.spec.ts
  src/app/shared/services/util/util.service.ts
Labels: ns:bar-web-pr-342

#341 [SCD][BAR-TESTS]
  src/app/core/components/check-submit/check-submit.component.spec.ts
  src/app/core/components/feelogedit/feelogedit.component.spec.ts
  src/app/core/components/login-form/login-form.component.spec.ts
  src/app/core/components/login-form/login-form.component.ts
  src/app/core/components/payment-instruction/payment-instruction.component.spec.ts
  src/app/core/components/payment-instruction/payment-instruction.component.ts
Labels: ns:bar-web-pr-341

#337 [SCD][BAR-339]
  src/app/core/components/payment-instruction/payment-instruction.component.html
Labels: ns:bar-web-pr-337

#335 BAR-386
  src/app/shared/components/details/details.component.ts
Labels: ns:bar-web-pr-335

#350 Bar 519
  README.md
  acceptance-tests/codecept.conf.js
  acceptance-tests/test/end-to-end/tests/BARDeliveryManager_test.js
  src/app/core/components/feelogedit/detail/feedetail.component.ts
  src/app/core/components/feelogedit/feelogedit.component.html
  src/app/core/components/feelogedit/feelogedit.component.spec.ts
  src/app/core/components/feelogedit/feelogedit.component.ts
  src/app/core/components/feelogedit/main/feelog.main.component.html
  src/app/core/components/feelogedit/main/feelog.main.component.ts
  src/app/core/components/search-results/search-results.component.html
  src/app/routes/routes.module.ts
  src/app/shared/components/details/details.component.scss
  src/app/shared/resolvers/payment-instruction.resolver.ts
  src/app/shared/shared.module.ts
  src/app/test-utils/test-utils.ts
  src/assets/stylesheets/app/_nav.scss
Labels: ns:bar-web-pr-350

#351 Fixed select all issue
  acceptance-tests/test/end-to-end/pages/steps_file.js
  src/app/core/components/check-submit/check-submit.component.spec.ts
  src/app/core/components/check-submit/check-submit.component.ts
  src/app/core/services/payment-instructions/payment-instructions.service.ts
  src/app/shared/components/details/details.component.html
  src/app/shared/components/details/details.component.spec.ts
  src/app/shared/components/details/details.component.ts
Labels: ns:bar-web-pr-351

#356 Select all issue
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/BARDeliveryManager_test.js
  acceptance-tests/test/end-to-end/tests/BARFeeClerk_test.js
  acceptance-tests/test/end-to-end/tests/BARPostClerk_test.js
Labels: ns:bar-web-pr-356

#357 Fixed unit tests
  src/app/core/components/check-submit/check-submit.component.spec.ts
  src/app/core/components/check-submit/check-submit.component.ts
  src/app/core/components/feelogedit/feelogedit.component.ts
  src/app/shared/components/stats/stats.component.ts
Labels: ns:bar-web-pr-357

#359 Fixed select all issue
  package.json
  src/app/core/components/check-submit/check-submit.component.ts
  src/app/core/components/feelogedit/detail/feedetail.component.html
  src/app/shared/components/details/details.component.ts
  src/app/test-utils/test-utils.ts
Labels: ns:bar-web-pr-359

#360 Fixed to check count
  src/app/core/components/check-submit/check-submit.component.ts
Labels: ns:bar-web-pr-360

#361 [BAR-528][AK] fix status changes
  src/app/core/components/feelogedit/feelogedit.component.ts
  src/app/shared/components/details/details.component.ts
Labels: ns:bar-web-pr-361

#362 Fixed tests
  src/app/core/components/feelogedit/feelogedit.component.spec.ts
  src/app/shared/directives/numbers-only/numbers-only.directive.spec.ts
Labels: ns:bar-web-pr-362
