Repository hmcts/bar-web, pull requests merged in 2019-05, with the labels that each got.

#437 [BAR-766][AK] fix back button on fee edit page
  src/app/core/components/feelogedit/detail/feedetail.component.ts
Labels: ns:bar-web-pr-437

#438 [BAR-769][AK] fix date and table formatting on senior fee clerks page
  src/app/shared/components/details/details.component.scss
Labels: ns:bar-web-pr-438

#435 [BAR-685] health check
  express/infrastructure/health-check.js
  express/services/UtilService.js
  package.json
  server.js
  sonar-project.properties
  yarn.lock
Labels: ns:bar-web-pr-435

#436 BAR-543 - Update validate payment screen after adding partial remission
  src/app/core/components/feelogedit/detail/feedetail.component.html
  src/app/core/components/feelogedit/feelogedit.component.scss
  src/app/core/components/feelogedit/main/feelog.main.component.html
  src/app/core/components/feelogedit/main/feelog.main.component.spec.ts
Labels: ns:bar-web-pr-436

#424 BAR-653 Adding calendar picker into the reporting form
  src/app/core/components/reporting/reporting.component.html
  src/app/core/components/reporting/reporting.component.spec.ts
  src/app/core/components/reporting/reporting.component.ts
Labels: ns:bar-web-pr-424

#443 [BAR-626] Assign multiple site for the same user
  express/app.js
  express/infrastructure/security.js
  express/mvc/controllers/SitesController.js
  express/mvc/controllers/index.js
  express/services/SitesService.js
  express/services/index.js
  express/test/mvc/controllers/SitesController.test.js
  express/test/services/SitesService.test.js
  src/app/app.module.ts
  src/app/core/models/sites.model.ts
  src/app/core/test-mocks/sites.service.mock.ts
  src/app/shared/components/navigation/navigation.component.html
  src/app/shared/components/navigation/navigation.component.scss
  src/app/shared/components/navigation/navigation.component.spec.ts
  src/app/shared/components/navigation/navigation.component.ts
  src/app/shared/services/sites/sites.service.spec.ts
  src/app/shared/services/sites/sites.service.ts
  src/app/shared/services/user/user.service.ts
Labels: ns:bar-web-pr-443

#450 [BAR-653][AK] add some more validation for the report date on angular side
  src/app/core/components/reporting/reporting.component.html
  src/app/core/components/reporting/reporting.component.spec.ts
  src/app/core/components/reporting/reporting.component.ts
Labels: ns:bar-web-pr-450
