Repository hmcts/bar-web, pull requests merged in 2019-07, with the labels that each got.

#477 BAR-785 implemented
  acceptance-tests/test/end-to-end/tests/BARMultisite_test.js
Labels: ns:bar-web-pr-477

#465 BAR-595 Error message changes
  src/app/core/components/feelogedit/main/feelog.main.component.ts
  src/app/test-utils/feelog-main-content.ts
Labels: ns:bar-web-pr-465

#478 BAR-803 804 implemented
  acceptance-tests/test/end-to-end/tests/BARMultisite_test.js
  express/services/PaymentsLogService.js
  express/test/services/PaymentsLogService.test.js
  src/app/core/components/search-results/search-results.component.html
  src/app/core/components/search-results/search-results.component.ts
  src/app/core/interfaces/payments-log.ts
  src/app/core/models/payhub-reference.model.ts
  src/app/core/models/payment-parent.model.ts
  src/app/test-utils/test-utils.ts
Labels: ns:bar-web-pr-478

#480 BAR-web improvements added.
  src/app/core/components/payment-overview/payment-overview.component.css
  src/app/core/components/payment-overview/payment-overview.component.html
  src/app/core/components/site-admin/site-admin.component.css
  src/app/core/components/site-admin/site-admin.component.html
  src/app/shared/components/navigation/navigation.component.html
  src/app/shared/components/navigation/navigation.component.scss
Labels: ns:bar-web-pr-480

#483 BAR-596 and BAR-597 changes added.
  src/app/core/components/feelogedit/feelogedit.component.scss
  src/app/core/components/feelogedit/feelogedit.component.ts
  src/app/core/components/feelogedit/main/feelog.main.component.html
  src/app/core/components/feelogedit/main/feelog.main.component.spec.ts
  src/app/core/components/feelogedit/main/feelog.main.component.ts
Labels: ns:bar-web-pr-483

#481 BAR-663 - Adding pound symbol for payment amount field
  src/app/core/components/payment-instruction/payment-instruction.component.html
  src/app/core/components/payment-instruction/payment-instruction.component.scss
Labels: ns:bar-web-pr-481

#482 BAR-599 Enable validation for withdrew option
  src/app/core/components/feelogedit/feelogedit.component.html
  src/app/core/components/feelogedit/feelogedit.component.ts
  src/app/core/components/feelogedit/main/feelog.main.component.html
  src/app/core/components/feelogedit/main/feelog.main.component.spec.ts
  src/app/core/components/feelogedit/main/feelog.main.component.ts
Labels: ns:bar-web-pr-482

#479 BAR-559 - Removing "Select" text and positioning "All" text
  src/app/core/components/paymentslog/paymentslog.component.css
  src/app/core/components/paymentslog/paymentslog.component.html
Labels: ns:bar-web-pr-479
