Repository hmcts/bar-web, pull requests merged in 2019-06, with the labels that each got.

#454 [BAR-768][AK] implement remove user from site
  express/app.js
  express/mvc/controllers/SitesController.js
  express/services/SitesService.js
  express/test/mvc/controllers/SitesController.test.js
  express/test/services/SitesService.test.js
  src/app/app.module.ts
  src/app/core/components/login-form/login-form.component.ts
  src/app/core/components/site-admin/site-admin.component.css
  src/app/core/components/site-admin/site-admin.component.html
  src/app/core/components/site-admin/site-admin.component.spec.ts
  src/app/core/components/site-admin/site-admin.component.ts
  src/app/core/models/sites.model.ts
  src/app/core/test-mocks/sites.service.mock.ts
  src/app/routes/routes.module.ts
  src/app/shared/components/navigation/navigation.component.html
  src/app/shared/components/navigation/navigation.component.spec.ts
  src/app/shared/components/navigation/navigation.component.ts
  src/app/shared/services/auth/host-based-guard.service.spec.ts
  src/app/shared/services/auth/host-based-guard.service.ts
  src/app/shared/services/sites/sites.service.spec.ts
  src/app/shared/services/user/user.service.spec.ts
  src/app/shared/services/user/user.service.ts
Labels: ns:bar-web-pr-454

#455 [BAR-561][AK] Remove separator lines when multiple fees attached
  src/app/core/interfaces/check-and-submit.ts
  src/app/core/models/check-and-submit.ts
  src/app/shared/components/details/details.component.html
  src/app/shared/components/details/details.component.scss
  src/app/shared/components/details/details.component.ts
  src/app/shared/components/payment-instruction-grid/payment-instruction-grid.component.html
  src/app/shared/components/payment-instruction-grid/payment-instruction-grid.component.scss
  src/app/shared/components/payment-instruction-grid/payment-instruction-grid.component.ts
Labels: ns:bar-web-pr-455

#456 upgrade libraries versions
  package.json
  yarn.lock
Labels: ns:bar-web-pr-456

#459 BAR-710 implemented
  acceptance-tests/test/end-to-end/pages/steps_file.js
  src/app/core/components/feelogedit/feelogedit.component.ts
  src/app/core/components/feelogedit/main/feelog.main.component.html
  src/app/core/components/payment-overview/payment-overview.component.spec.ts
  src/app/shared/components/navigation/navigation.component.html
  src/app/shared/components/navigation/navigation.component.spec.ts
  src/app/shared/components/navigation/navigation.component.ts
Labels: ns:bar-web-pr-459

#458 BAR-792 implemented
  src/app/core/components/payment-instruction/payment-instruction.component.spec.ts
  src/app/core/components/payment-instruction/payment-instruction.component.ts
Labels: ns:bar-web-pr-458

#457 Code changes for BAR-669 in payment entry confirmation page
  src/app/core/components/payment-instruction/payment-instruction.component.html
Labels: ns:bar-web-pr-457

#461 [BAR-657][AK] Mapping of status labels to a different one
  src/app/app.module.ts
  src/app/core/components/search-results/search-results.component.html
  src/app/core/components/search-results/search-results.component.scss
  src/app/shared/components/navigation/navigation.component.html
  src/app/shared/directives/map-status-label/map-status-label.directive.spec.ts
  src/app/shared/directives/map-status-label/map-status-label.directive.ts
Labels: ns:bar-web-pr-461

#462 multisite functional tests
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/BARDeliveryManager_test.js
  acceptance-tests/test/end-to-end/tests/BARMutlisite_test.js
  src/app/core/components/login-form/login-form.component.ts
  src/app/shared/services/user/user.service.ts
Labels: ns:bar-web-pr-462

#467 BAR-641 Inconsistent title changes
  acceptance-tests/test/end-to-end/pages/steps.js
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/BARMutlisite_test.js
  acceptance-tests/test/end-to-end/tests/BARPostClerk_test.js
  src/app/core/components/payment-instruction-list/payment-instruction-list.component.html
  src/app/core/components/payment-instruction/payment-instruction.component.html
  src/app/core/components/payment-instruction/payment-instruction.component.ts
  src/app/core/components/paymentslog/paymentslog.component.html
Labels: ns:bar-web-pr-467

#469 BAR-643 Reporting changes
  src/app/core/components/reporting/reporting.component.html
Labels: ns:bar-web-pr-469
