Repository hmcts/bar-web, pull requests merged in 2019-04, with the labels that each got.

#410 [BAR-718][AK] Rejected withdraw item was not editable
  Jenkinsfile_CNP
  kubernetes/config.aat.yaml
  src/app/core/components/check-submit/check-submit.component.spec.ts
  src/app/core/components/feelogedit/main/feelog.main.component.html
  src/app/core/components/login-form/login-form.component.html
  src/app/core/components/login-form/login-form.component.ts
  src/app/shared/services/user/user.service.ts
  src/app/shared/services/util/util.service.ts
Labels: ns:bar-web-pr-410

#413 BAR-707 implemented
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/BARFeeClerk_test.js
Labels: ns:bar-web-pr-413

#417 bar-web helm chart
  Jenkinsfile_CNP
  acceptance-tests/helper/Helpers.js
  acceptance-tests/test/end-to-end/tests/BARDeliveryManager_test.js
  bin/run-functional-tests.sh
  charts/bar-web/Chart.yaml
  charts/bar-web/requirements.yaml
  charts/bar-web/values.aat.template.yaml
  charts/bar-web/values.template.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  kubernetes/.lint.yml
  kubernetes/config.aat.yaml
  kubernetes/deployment.template.yaml
  package.json
  src/app/core/components/login-form/login-form.component.html
  src/app/core/components/login-form/login-form.component.ts
  src/app/core/components/payment-instruction/payment-instruction.component.ts
  src/app/shared/services/user/user.service.ts
  yarn.lock
Labels: ns:bar-web-pr-417

#420 Bar web demo repoint
  charts/bar-web/requirements.yaml
  infrastructure/demo.tfvars
Labels: ns:bar-web-pr-420

#423 [BAR-565] Close remission section if not needed
  src/app/core/components/feelogedit/detail/feedetail.component.ts
Labels: ns:bar-web-pr-423

#422 BAR-566,567,569 implemented
  src/app/core/components/feelogedit/detail/feedatail.validator.ts
  src/app/core/components/feelogedit/detail/feedetail.component.html
  src/app/core/components/feelogedit/detail/feedetail.component.spec.ts
  src/app/core/components/feelogedit/detail/feedetail.component.ts
Labels: ns:bar-web-pr-422

#426 [BAR-562][AK] Case reference proper validation
  express/mvc/controllers/FeeController.js
  src/app/core/components/feelogedit/detail/feedatail.validator.ts
  src/app/core/components/feelogedit/detail/feedetail.component.spec.ts
Labels: ns:bar-web-pr-426

#427 [BAR-728][BAR-674][AK] Search result page fixes
  .nvmrc
  .travis.yml
  src/app/core/components/search-results/search-results.component.html
  src/app/core/components/search-results/search-results.component.scss
  src/app/core/components/search-results/search-results.component.spec.ts
  src/app/core/components/search-results/search-results.component.ts
Labels: ns:bar-web-pr-427

#425 [BAR-614] Optimise nodejs logging
  express/infrastructure/errors.js
  express/infrastructure/security.js
  express/mvc/controllers/PaymentsOverviewController.js
  express/test/infratructure/errors.test.js
  express/test/mvc/controllers/PaymentsOverviewController.test.js
  server.js
Labels: ns:bar-web-pr-425
