Repository hmcts/bar-web, pull requests merged in 2019-03, with the labels that each got.

#398 fix url mapping on app side and using the new url here
  express/infrastructure/security.js
Labels: ns:bar-web-pr-398

#393 [BAR-690][AK] Speed up payment instruction load with Idam user details request caching
  express/infrastructure/security.js
  package.json
  yarn.lock
Labels: ns:bar-web-pr-393

#399 BAR-606,608,609 Implemented
  acceptance-tests/test/end-to-end/pages/steps.js
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/BARPostClerk_test.js
  src/app/core/components/payment-instruction/payment-instruction.component.html
  src/app/core/components/payment-instruction/payment-instruction.component.ts
  src/app/shared/components/navigation/navigation.component.html
Labels: ns:bar-web-pr-399

#395 [BAR-690][AK] Introduce caching in angular for the reference data
  src/app/app.module.ts
  src/app/core/components/payment-review-summary/payment-review-summary.component.ts
  src/app/core/test-mocks/paymentstate.service.mock.ts
  src/app/shared/components/action-filter/action-filter.component.ts
  src/app/shared/components/stats/stats.component.html
  src/app/shared/components/stats/stats.component.ts
  src/app/shared/services/action/paymentaction.service.spec.ts
  src/app/shared/services/action/paymentaction.service.ts
  src/app/shared/services/cache/cache.service.ts
  src/app/shared/services/feature/feature.service.spec.ts
  src/app/shared/services/feature/feature.service.ts
  src/app/shared/services/state/paymentstate.service.spec.ts
  src/app/shared/services/state/paymentstate.service.ts
Labels: ns:bar-web-pr-395

#404 Update saat.tfvars
  infrastructure/saat.tfvars
Labels: ns:bar-web-pr-404

#405 Update saat.tfvars
  infrastructure/saat.tfvars
Labels: ns:bar-web-pr-405

#396 [BAR-702][AK] prevent user from double click "Add Payment" button
  src/app/core/components/payment-instruction/payment-instruction.component.html
  src/app/core/components/payment-instruction/payment-instruction.component.spec.ts
  src/app/core/components/payment-instruction/payment-instruction.component.ts
Labels: ns:bar-web-pr-396

#408 [BAR-713] fix error display issue on edit component
  src/app/core/components/feelogedit/feelogedit.component.spec.ts
  src/app/core/components/feelogedit/feelogedit.component.ts
  src/app/core/components/feelogedit/main/feelog.main.component.html
  src/app/core/components/feelogedit/main/feelog.main.component.spec.ts
  src/app/core/components/feelogedit/main/feelog.main.component.ts
Labels: ns:bar-web-pr-408

#397 [BAR-588][AK] add counter on fee clerk check and submit page
  src/app/core/components/check-submit/check-submit.component.html
  src/app/core/components/check-submit/check-submit.component.spec.ts
  src/app/core/components/check-submit/check-submit.component.ts
  src/app/core/components/login-form/login-form.component.html
  src/app/core/components/login-form/login-form.component.ts
  src/app/core/components/payment-review-summary/payment-review-summary.component.html
  src/app/core/components/payment-review-summary/payment-review-summary.component.spec.ts
  src/app/core/components/payment-review-summary/payment-review-summary.component.ts
  src/app/core/services/paymentoverview/paymentsoverview.service.ts
  src/app/shared/components/action-filter/action-filter.component.html
  src/app/shared/components/action-filter/action-filter.component.spec.ts
  src/app/shared/components/action-filter/action-filter.component.ts
Labels: ns:bar-web-pr-397

#409 remove user id validation
  express/app.js
Labels: ns:bar-web-pr-409

#411 update idam url to the strategic one on aat
  infrastructure/aat.tfvars
Labels: ns:bar-web-pr-411
