Repository hmcts/bar-web, pull requests merged in 2022-06, with the labels that each got.

#732 new changes
  yarn-audit-known-issues
Labels: ns:bar, prd:bar, rel:bar-web-pr-732

#734 Suppress security on audit file
  audit.json
Labels: ns:bar, prd:bar, rel:bar-web-pr-734

#735 Upgrade to codeceptjs 3 add implement cross browser tests
  Jenkinsfile_nightly
  acceptance-tests/codecept.conf.js
  acceptance-tests/helper/SauceLabsReportingHelper.js
  acceptance-tests/saucelabs.conf.js
  acceptance-tests/test/end-to-end/config/BARConfig.js
  acceptance-tests/test/end-to-end/crossbrowser/supportedBrowsers.js
  acceptance-tests/test/end-to-end/tests/BARDeliveryManager_test.js
  acceptance-tests/test/end-to-end/tests/BARFeeClerk_test.js
  acceptance-tests/test/end-to-end/tests/BARMultisite_test.js
  acceptance-tests/test/end-to-end/tests/BARPostClerk_test.js
  bin/run-crossbrowser-tests.sh
  package.json
  smoke-test/test/smoke-test.js
  yarn.lock
Labels: ns:bar, prd:bar, rel:bar-web-pr-735
