Repository hmcts/bar-web, pull requests merged in 2023-01, with the labels that each got.

#755 suppress cve
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:bar, prd:bar, rel:bar-web-pr-755

#758 cve fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:bar, prd:bar, rel:bar-web-pr-758

#759 disable fortify scan
  Jenkinsfile_nightly
Labels: ns:bar, prd:bar, rel:bar-web-pr-759

#760 handle 403 error as it is instead of 500.
  express/mvc/controllers/PaymentInstructionController.js
Labels: ns:bar, prd:bar, rel:bar-web-pr-760

#761 updated deprecated after to afterAlways
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  charts/bar-web/Chart.yaml
  package.json
  yarn.lock
Labels: ns:bar, prd:bar, rel:bar-web-pr-761

#763 Upgraded Terraform version to 1.3.7
  infrastructure/.terraform-version
Labels: ns:bar, prd:bar, no-changes, rel:bar-web-pr-763
