Repository hmcts/bar-web, pull requests merged in 2023-09, with the labels that each got.

#789 PAY-6510: Nightly build pipeline fixes
  audit.json
Labels: ns:bar, prd:bar, rel:bar-web-pr-789

#790 https://tools.hmcts.net/jira/browse/PAY-6518
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:bar, prd:bar, rel:bar-web-pr-790

#792 Addingrenovate.json
  .github/renovate.json
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:bar, prd:bar, rel:bar-web-pr-792

#798 fix for shell script
  audit.json
Labels: ns:bar, prd:bar, rel:bar-web-pr-798

#800 security issue fixed
  audit.json
Labels: ns:bar, prd:bar, rel:bar-web-pr-800
