Repository hmcts/bar-web, pull requests merged in 2024-04, with the labels that each got.

#827 PAY-6974 use express 4.19.2
  package.json
  yarn.lock
Labels: ns:bar, prd:bar, rel:bar-web-pr-827

#829 [PAY-6999: Pipeline fixes - week beginning 8th April 2024
  package.json
  yarn.lock
Labels: ns:bar, prd:bar, rel:bar-web-pr-829

#834 PAY-6982 Node version update and stale.yml file addition
  .github/workflows/stale.yml
  charts/bar-web/Chart.yaml
Labels: ns:bar, prd:bar, rel:bar-web-pr-834

#832 Feature/pay 6749 footer
  angular.json
  gulpfile.js
  package.json
  sonar-project.properties
  src/app/app.component.html
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/core/components/accessibility-statement/accessibility-statement.component.html
  src/app/core/components/accessibility-statement/accessibility-statement.component.spec.ts
  src/app/core/components/accessibility-statement/accessibility-statement.component.ts
  src/app/core/components/cookie-banner/cookie-banner.component.spec.ts
  src/app/core/components/cookie-banner/cookie-banner.component.ts
  src/app/core/components/cookie-policy/cookie-policy.component.html
  src/app/core/components/cookie-policy/cookie-policy.component.spec.ts
  src/app/core/components/cookie-policy/cookie-policy.component.ts
  src/app/routes/routes.module.ts
  src/app/shared/components/footer/footer.component.html
  src/app/shared/components/footer/footer.component.spec.ts
  src/app/shared/components/footer/footer.component.ts
  src/app/shared/components/footer/footer.model.ts
  src/app/shared/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/app/shared/components/hmcts-global-footer/hmcts-global-footer.component.spec.ts
  src/app/shared/components/hmcts-global-footer/hmcts-global-footer.component.ts
  src/assets/images/govuk-crest-2x.png
  src/assets/images/govuk-crest.png
  src/assets/images/open-government-licence_2x.png
  src/assets/js/cookie-manager-1.0.0.min.js
  src/assets/js/cookie.js
  src/assets/stylesheets/app/_nav.scss
  src/assets/stylesheets/main.css
  src/assets/stylesheets/main.scss
  src/index.html
  yarn-audit-known-issues
  yarn.lock
Labels: ns:bar, prd:bar, enable_keep_helm, rel:bar-web-pr-832
