Repository hmcts/bar-web, pull requests merged in 2024-05, with the labels that each got.

#838 Fix FTs as per Fee changes
  Jenkinsfile_nightly
  acceptance-tests/helper/utils.js
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/BARFeeClerk_test.js
  acceptance-tests/test/end-to-end/tests/BARMultisite_test.js
  acceptance-tests/test/end-to-end/tests/DuplicateTests.js
Labels: ns:bar, prd:bar, rel:bar-web-pr-838

#841 PAY-7093: Squash critical
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:bar, prd:bar, rel:bar-web-pr-841

#839 Pay 7021 angular upgrade
  README.md
  angular.json
  package.json
  src/app/core/components/accessibility-statement/accessibility-statement.component.html
  yarn.lock
Labels: ns:bar, prd:bar, keep-helm, enable_keep_helm, rel:bar-web-pr-839
