Repository hmcts/bar-web, pull requests merged in 2024-02, with the labels that each got.

#823 PAY-6866_CVE-2023-42282
  yarn-audit-known-issues
Labels: ns:bar, prd:bar, rel:bar-web-pr-823

#824 PAY-6871-CVE-2023-42282
  yarn-audit-known-issues
Labels: ns:bar, prd:bar, rel:bar-web-pr-824

#825 PAY-6908: Update to resolve CVEs
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:bar, prd:bar, rel:bar-web-pr-825
